version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  target-branch: master
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  target-branch: master
  allow:
  - dependency-type: direct
  - dependency-type: indirect